#!/bin/sh

set -e

case "$1" in
    purge)
	if which ucfr >/dev/null; then
		ucfr --purge dma /etc/dma/dma.conf
	fi
	if which ucf >/dev/null; then
		ucf --purge /etc/dma/dma.conf
	fi
	if [ -d /etc/dma ] ; then
		rm -rf /etc/dma || true
	fi
	if [ -d /var/spool/dma ] ; then
		rm -rf /var/spool/dma || true
	fi
    ;;
esac

#DEBHELPER#
