#!/bin/ksh

TARGET="$1"	# target for destdir

# Install library headers first
inst_hdr() {
	
	cd usr/include/base && \
		make DESTDIR="$TARGET" && \
		cd ../../../
}

# build source
src_build() {
	local _dirs
	set -A _dirs -- lib bin usr/bin

	for dir in "${_dirs[@]}"; do
		cd "$dir" && \
			chmod +x build && \
			./build "$TARGET" && \
			cd ..
	done
}

inst_hdr
src_build
