# Makefile for man
# $Ragnarok: Makefile,v 1.4 2024/05/19 16:09:22 lecorbeau Exp $

all:
	@echo "Nothing to make, skipping..."

install:
	install -d ${DESTDIR}/usr/share/man/man8
	install man8/afterboot.8 ${DESTDIR}/usr/share/man/man8
	install man8/kernupd.8 ${DESTDIR}/usr/share/man/man8
