# Makefile for man
# $Ragnarok: Makefile,v 1.5 2024/11/09 18:36:59 lecorbeau Exp $

all:
	@echo "Nothing to make, skipping..."

install:
	install -d ${DESTDIR}/usr/share/man/man8
	install man8/afterboot.8 ${DESTDIR}/usr/share/man/man8
