#!/bin/sh

# Script to perform some basic security checks on a weekly basic.
# $Ragnarok: security-check,v 1.2 2024/09/24 18:43:53 lecorbeau Exp $

# Note: at some point simplify this script by creating functions rather
# than repeating the same shit over and over again.

# Can't run as non-root user
if [ "$(id -u)" -ne 0 ]; then
	printf '%s\n' "Only root can execute this script"
	exit 1
fi

printf '%s\n' "Checking for issues with file permissions..."

# There is no chance this directory contains files with spaces in their
# names (if there are any, this is a user error) so disable useless shellcheck
# error.
# shellcheck disable=SC2044
for _file in $(find /etc/network/interfaces.d/ -type f); do
	if [ "$(stat -c "%a %g %G" "$_file")" != "600 0 root" ]; then
		/usr/bin/chmod 600 "$_file"
		/usr/bin/chown root:root "$_file"
		printf '%s\n' "Fixed ${_file}'s permissions."
	else
		printf '%s\n' "${_file}'s permissions are OK."
	fi
done

# nftables.conf should have 700 bits
if [ "$(stat -c "%a %g %G" /etc/nftables.conf)" != "700 0 root" ]; then
	/usr/bin/chmod 700 /etc/nftables.conf
	/usr/bin/chown root:root /etc/nftables.conf
	printf '%s\n' "Fixed /etc/nftable's permissions."
else
	printf '%s\n' "/etc/nftable.conf's permissions are OK."
fi

# sysctl config must have 600 bits. # shellcheck disable=SC2044
for _file in $(find /etc/sysctl.d -type f ! -name README.sysctl) /etc/sysctl.conf; do
	if [ "$(stat -c "%a %g %G" "$_file")" != "600 0 root" ]; then
		/usr/bin/chmod 600 "$_file"
		/usr/bin/chown root:root "$_file"
		printf '%s\n' "Fixed ${_file}'s permissions."
	else
		printf '%s\n' "${_file}'s permissions are OK."
	fi
done

# Bootloader files should have 600 perms.
# Only check if they exist.
if [ -d "/boot/grub/" ]; then
	for _file in /boot/grub/custom.cfg /etc/default/grub.d/01_hardening.cfg; do
		if [ "$(stat -c "%a %g %G" "$_file")" != "600 0 root" ]; then
			/usr/bin/chmod 600 "$_file"
			/usr/bin/chown root:root "$_file"
			printf '%s\n' "Fixed ${_file}'s permissions."
		else
			printf '%s\n' "${_file}'s permissions are OK."
		fi
	done
fi

if [ -d "/boot/syslinux/" ]; then
	if [ "$(stat -c "%a %g %G" /boot/syslinux/syslinux.cfg)" != "600 0 root" ]; then
		/usr/bin/chmod 600 /boot/syslinux/syslinux.cfg
		/usr/bin/chown root:root /boot/syslinux/syslinux.cfg
		printf '%s\n' "Fixed /boot/syslinux/syslinux.cfg's permissions."
	else
		printf '%s\n' "/boot/syslinux/syslinux.cfg's permissions are OK."
	fi
fi
