#!/bin/sh

# $Ragnarok: vmlaunch,v 1.1 2024/06/22 14:36:26 lecorbeau Exp $
#
# Example script: launch a live ISO (e.g. live01-amd64.hybrid.iso) in a
# virtual machine using QEMU directly, without graphics support.
#
# The 'q35' machine may need to be changed. Using the command
#
# 	qemu-system-x86_64 -machine help
#
# will show available machine types. The one marked as '(default)' is
# usually a good choice.
#
# Script usage:
#
# 	vmlaunch ~/Downloads/live01-amd64.hybrid.iso

_iso=$1

/usr/bin/qemu-system-x86_64 -machine q35 -accel kvm -net nic -net user \
	-m 2048 -drive file="$_iso",media=cdrom,format=raw -nographic \
	-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny

