# Makefile for /usr/lib
# $Ragnarok: Makefile,v 1.8 2024/03/04 17:44:17 lecorbeau Exp i $

all: install

install:
	install -d ${DESTDIR}/usr/lib
	install ragnarok-shlib ${DESTDIR}/usr/lib
	#cp -r hardened_malloc ${DESTDIR}/usr/lib/
