.Dd August 5, 2019
.Dt INIT\-D\-SCRIPT 5 "Debian sysvinit"
.Os Debian
.Sh NAME
.Nm init\-d\-script
.Nd interpreter for short and simple init.d scripts
.Sh DESCRIPTION
Generic init.d script framework to reduce the redundant code in
.Pa /etc/init.d/ .
The goal is to create an init.d script that is Debian and LSB compliant.
When the Debian policy conflicts with the LSB, the Debian policy takes
precedence.
.Pp
This is a simple example on how init\-d\-script can be used to start
and stop a daemon with PID file support:
.Bd -literal -offset indent
#!/bin/sh /lib/init/init\-d\-script
### BEGIN INIT INFO
# Provides:          atd
# Required\-Start:    $syslog $time $remote_fs
# Required\-Stop:     $syslog $time $remote_fs
# Default\-Start:     2 3 4 5
# Default\-Stop:      0 1 6
# Short\-Description: run at jobs
# Description:       Debian init script to start the daemon
#                    running at jobs.
### END INIT INFO
DAEMON=/usr/sbin/atd
.Ed
.Pp
The following variables affect behaviour of an init script:
.Bl -tag -width "RELOAD_SIGNAL"
.It Ev DAEMON
Path to daemon being started.
If the init script is not supposed to start any kind of daemon,
it should be set to
.Dq Li none
and the functions
.Fn do_start_override ,
.Fn do_stop_override
and
.Fn do_status_override
should be defined instead.
.It Ev DAEMON_ARGS
Additional arguments, passed to daemon during start.
.It Ev DESC
Full name or short description of the daemon, printed on screen.
If unset, this variable defaults to the
.Dq Ev NAME
value.
.It Ev NAME
Additional environment variables are sourced from
.Pa /etc/default/${NAME} .
If unset, this variable defaults to the basename of the
.Dq Ev DAEMON
value.
.It Ev COMMAND_NAME
If this variable is set, it is used as argument to the
.Fl \-name
option of
.Xr start\-stop\-daemon 8 .
It may be useful if the value of the
.Dq Ev NAME
variable is longer than the command name length supported by
the running kernel.
If the value is verbatim
.Dq Li none ,
the command name will not be used to match the processes.
If unset, this variable defaults to the
.Dq Ev NAME
value.
.It Ev PIDFILE
Path to file where the process identifier of the started daemon
will be stored during start.
If the value is verbatim
.Dq Li none ,
the process identifier will not be stored in any file.
If this variable is not set, it gets a sensible default value,
so it is rarely necessary to set this variable explicitly.
.It Ev RELOAD_SIGNAL
Signal number or name (without the SIG prefix) that will be sent to
the process on
.Ic reload .
If the daemon performs reload action upon receiving a
.Dv SIGHUP
signal, this variable should be set to
.Dq Li 1
or
.Dq Li HUP .
.El
.Pp
The variables
.Ev RELOAD_ARGS ,
.Ev START_ARGS
and
.Ev STOP_ARGS
are additional arguments, passed to
.Xr start\-stop\-daemon 8
during reload, start and stop actions, to override the default options.
.Pp
Additionally, it is possible to change the behaviour of the resulting
shell script by overriding some of the internal functions.
To do so, define function with an
.Ic _override
suffix.
So, for example, to override the
.Fn do_status
function, one should define a
.Fn do_status_override
function.
The
.Em exception
to this rule is the
.Fn do_reload
function, whose override should be defined as-is,
.Em without
the above-mentioned suffix.
.Pp
Here is a control flow chart that explains what functions are called and when:
.Bd -literal -offset indent
/etc/init.d/script start
  do_start
    do_start_prepare # no-op
    do_start_cmd     # start\-stop\-daemon is called here
    do_start_cleanup # no-op

/etc/init.d/script stop
  do_stop
    do_stop_prepare # no-op
    do_stop_cmd     # start\-stop\-daemon is called here
    do_stop_cleanup # no-op

/etc/init.d/script status
  do_status

/etc/init.d/script reload
  do_reload
    do_usage
    exit 3

/etc/init.d/script force\-reload
  do_force_reload
    do_reload   # if overridden
    do_restart
      do_restart_prepare
      do_stop_cmd
      do_start_cmd
      do_restart_cleanup

/etc/init.d/script restart
  do_force_restart
/etc/init.d/script try\-restart
  if do_status; then
    do_restart
      do_restart_prepare
      do_stop_cmd  # start\-stop\-daemon is called here
      do_start_cmd # start\-stop\-daemon is called here
      do_restart_cleanup

/etc/init.d/script \*(Ltarg\*(Gt
  do_unknown \*(Ltarg\*(Gt
    exit 3

/etc/init.d/script
  do_usage
.Ed
.Pp
As can be seen, by default, the script does not support the
.Ic reload
action; it should be implemented by the script writer by defining a
.Fn do_reload
function.
.Pp
If
.Fn do_reload
is not defined but
.Fn do_reload_cmd
is, the latter will be called on
.Ic reload ,
after
.Fn do_reload_prepare
and before
.Fn do_reload_cleanup .
.Sh SEE ALSO
.Xr inittab 8 ,
.Xr service 8 ,
.Xr update\-rc.d 8 .
.Sh AUTHORS
.An -nosplit
.An Petter Reinholdtsen Aq pere@debian.org
