#!/bin/sh
### BEGIN INIT INFO
# Provides:		rm-machineid
# Required-Start:
# Required-Stop:	
# Default-Start:
# Default-stop:		0 6
# Short-Description:	execute the rm-machineid script
# Description:
### END INIT INFO

# /etc/machine-id and /var/lib/dbus/machine-id can be used to fingerprint a system.
# Removing it when powering off or rebooting a machine will cause dbus to regenerate
# it on boot, which at least provides some sort of mitigation.

echo "removing machine-id"

# on non-systemd systems, this file doesn't exist (normally)
if [ -f /etc/machine-id ]; then
	rm -f /etc/machine-id
fi

rm -f /var/lib/dbus/machine-id
