#!/bin/sh

# hardened_malloc init script
# $Ragnarok: hardened_malloc,v 1.2 2024/07/03 15:54:52 lecorbeau Exp $

### BEGIN INIT INFO
# Provides:		hardened_malloc
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	enable hardened_malloc() at boot time
# Description:		fixes the long boot/poweroff times in the live iso.
### END INIT INFO

. /usr/lib/ragnarok-shlib

VARIANT=$(getvar VARIANT /etc/default/hardened_malloc)

do_start() {
	/usr/bin/printf '%s\n' "enabling the hardened memory allocator..."
	/usr/bin/ln -sf /usr/lib/hardened_malloc/libhardened_malloc-"${VARIANT}".so \
		/usr/lib/libhardened_malloc.so
	/usr/bin/echo "/usr/lib/libhardened_malloc.so" > /etc/ld.so.preload
}

do_stop() {
	/usr/bin/printf '%s\n' "disabling the hardened memory allocator..."
	/usr/bin/echo "" > /etc/ld.so.preload
	/usr/bin/rm /usr/lib/libhardened_malloc.so
}

do_check_status() {
	ldd /usr/bin/ls | grep "hardened" && exit 0 || exit $?
}

case "$1" in
	start) do_start ;;
	stop) do_stop ;;
	status) do_check_status ;;
esac
