# Makefile for man
# $Ragnarok: Makefile,v 1.3 2024/03/13 16:55:55 lecorbeau Exp $

all:
	@echo "Nothing to make, skipping..."

install:
	install -d ${DESTDIR}/usr/share/man/man8
	install man8/kernupd.8 ${DESTDIR}/usr/share/man/man8
