.TH HWCLOCK 5 "Dec 2020" "" "Debian Administrator's Manual"
.SH NAME
hwclock \- settings that affect the behaviour of the hwclock init script
.SH DESCRIPTION
The
.I /etc/default/hwclock
file contains settings in POSIX format:
.IP "" .5i
VAR=VAL
.PP
Only one assignment is allowed per line.
Comments (starting with '#') are also allowed.

.SH SETTINGS
The following settings can be set.

.IP \fBHCTOSYS_DEVICE\fP
The hardware clock device you want to use.  Defaults to \fBrtc0\fP.
It should probably match the CONFIG_RTC_HCTOSYS_DEVICE kernel config
option.

If you change this, you also need to install a custom udev rule,
mirroring \fB/usr/lib/udev/rules.d/85-hwclock.rules\fP. Otherwise,
the hardware clock device will be ignored during boot.

On almost all systems, this should not be changed.

.SH NOTES

On systems using systemd as init, the hwclock init script is ignored.

.SH SEE ALSO
.BR hwclock (8),
.BR systemd-timesyncd.service (8)
