#!/bin/sh

# Script to be run when the system boots up the first time after install.
# $Ragnarok: firstboot,v 1.3 2024/07/08 20:01:28 lecorbeau Exp $
#
### BEGIN INIT INFO
# Provides:		first boot script
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-stop:		
# Short-Description:	execute commands after system's first boot
# Description:
### END INIT INFO

# Function to build hardened_malloc. 
build_hm() {

	DIR="/usr/src/hardened_malloc"

	/usr/bin/make -C "$DIR" -j"$(nproc)"
	/usr/bin/make -C "$DIR" VARIANT=medium -j"$(nproc)"
	/usr/bin/make -C "$DIR" VARIANT=light -j"$(nproc)"

	/usr/bin/mkdir -p /usr/lib/hardened_malloc
	/usr/bin/mv "$DIR"/out-strong/libhardened_malloc-strong.so /usr/lib/hardened_malloc/
	/usr/bin/mv "$DIR"/out-medium/libhardened_malloc-medium.so /usr/lib/hardened_malloc/
	/usr/bin/mv "$DIR"/out-light/libhardened_malloc-light.so /usr/lib/hardened_malloc/	
}

# Mail install.log
/usr/bin/cat /var/messages/install.log | mail -r installer@ragnarok -s "Installation log" root

# Handle hardened_malloc. We can only build it if the devel set was installed.
if command -v /usr/bin/clang; then
	/usr/bin/printf '%s\n' "Building hardened_malloc..."
	build_hm | /usr/bin/mail -r root@ragnarok -s "hardened_malloc build log" root
	/usr/bin/printf '%s\n' "hardened_malloc built. See the HARDENED_MALLOC section
in the afterboot(8) manual for details on how to enable it."
fi

# Security check. Ensure some files have the right permissions.


# do other stuff ...

# In the end, this script needs to disable itself
/usr/sbin/update-rc.d firstboot defaults-disabled

