#!/bin/sh

# Script to be run when the system boots up the first time after install.
# $Ragnarok: firstboot,v 1.5 2024/07/15 17:27:57 lecorbeau Exp $
#
### BEGIN INIT INFO
# Provides:		first boot script
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-stop:		
# Short-Description:	execute commands after system's first boot
# Description:
### END INIT INFO

# Function to build hardened_malloc. 
build_hm() {

	DIR="/usr/src/hardened_malloc"

	/usr/bin/make -C "$DIR" -j"$(nproc)"
	/usr/bin/make -C "$DIR" VARIANT=medium -j"$(nproc)"
	/usr/bin/make -C "$DIR" VARIANT=light -j"$(nproc)"

	/usr/bin/mkdir -p /usr/lib/hardened_malloc
	/usr/bin/mv "$DIR"/out-strong/libhardened_malloc-strong.so /usr/lib/hardened_malloc/
	/usr/bin/mv "$DIR"/out-medium/libhardened_malloc-medium.so /usr/lib/hardened_malloc/
	/usr/bin/mv "$DIR"/out-light/libhardened_malloc-light.so /usr/lib/hardened_malloc/	
}

prt_msg() {
	printf '%s\n' "
Welcome to Ragnarok

$(lsb_release -a 2>/dev/null)
Installed on:	$(date)

If you have not done so already, it is highly recommended to read the
afterboot(8) manual page.

If youy encouter any bugs, please report them in the issue tracker of
the appropriate repository at https://github.com/RagnarokOS/.
" > /var/messages/welcome.txt
}

# ensure /var/messages exists
/usr/bin/mkdir -p /var/messages

# Mail install.log
/usr/bin/cat /var/messages/install.log | mail -r installer@ragnarok -s "Installation log" root

# Mail welcome message
prt_msg
/usr/bin/cat /var/messages/welcome.txt | /usr/bin/mail -r "LeCorbeau@ragnarok" -s "Welcome" root

# Handle hardened_malloc. We can only build it if the devel set was installed.
if command -v /usr/bin/clang; then
	/usr/bin/printf '%s\n' "Building hardened_malloc..."
	build_hm | /usr/bin/mail -r root@ragnarok -s "hardened_malloc build log" root
	/usr/bin/printf '%s\n' "hardened_malloc built. See the HARDENED_MALLOC section
in the afterboot(8) manual for details on how to enable it."
fi

# Run the security-check cron job right away.
/etc/cron.weekly/security-check

# do other stuff ...

# In the end, this script needs to disable and remove itself.
/usr/sbin/update-rc.d -f firstboot remove
