# Makefile for the boot directory
# $Ragnarok: Makefile,v 1.3 2024/03/04 17:50:01 lecorbeau Exp $

all: install

install:
	install -d ${DESTDIR}/boot/grub
	install grub/custom.cfg ${DESTDIR}/boot/grub

