#!/bin/sh

PKG_NAME="base-files"

# Fetch the source, install build dependencies and copy the control/changelog files.
prepare() {
	apt-get source "$PKG_NAME"
	apt-get build-dep "$PKG_NAME"
	cp ragnarok/control "$PKG_NAME"-*/debian/
	cp ragnarok/changelog "$PKG_NAME"-*/debian/
}

# Apply patches, if there are any.
do_patch() {
	for _file in ragnarok/*.diff; do
		if [ -f "$_file" ]; then
			cd "$PKG_NAME"-* && \
				for _patch in ../ragnarok/*.diff; do patch -p1 < "$_patch"; done && \
					cd ..
		fi
	done
}

# Build the package
do_build() {
	prepare
	do_patch
	cd "$PKG_NAME"-* && debuild -i -us -uc -b && cd ..
}

# Update package to new version
do_update() {
	prepare
	cd "$PKG_NAME"-* && dch -n && cd ..
	cp "$PKG_NAME"-*/debian/changelog ragnarok/
	cp "$PKG_NAME"-*/debian/control ragnarok/
	do_patch
	cd "$PKG_NAME"-* && debuild -i -us -uc -b && cd ..
}

# Move all deb/udeb packages to a directory named pkgs
mvpkg() {
	mkdir -p ../pkgs
	for _pkg in *.deb; do mv "$_pkg" ../pkgs/; done
}

# Clean the directory.
cleanup() {
	mvpkg
	rm -rf "$PKG_NAME"-*
	for _file in "$PKG_NAME"_*; do rm "$_file"; done
}

case $1 in
	-c) cleanup ;;
	-u) do_update && cleanup ;;
	*) do_build && cleanup ;;
esac
