# Makefile for /usr/share/mk
# $Id: Makefile,v 1.3 2024/03/04 17:46:44 lecorbeau Exp $

FILES = libs.mk progs.mk ragnarok-config.mk

all: install

install:
	install -d ${DESTDIR}/usr/share/mk
	install ${FILES} ${DESTDIR}/usr/share/mk
