#! /bin/sh
### BEGIN INIT INFO
# Provides:          reboot
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO

PATH=/usr/sbin:/usr/bin:/sbin:/bin

. /lib/lsb/init-functions
[ -f /etc/default/halt ] && . /etc/default/halt

do_stop () {
	# Message should end with a newline since kFreeBSD may
	# print more stuff (see #323749)
	log_action_msg "Will now restart"
	local netdown="-i"
	if [ "${NETDOWN}" = no ] ; then
		netdown=""
	fi
	reboot -d -f ${netdown}
}

case "$1" in
  start)
	# No-op
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  status)
	exit 0
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
